### ISSUE TITLE
bedrock2 extraction tracker issue

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#524]
It would be cool to generate bedrock2 code from fiat-crypto. I think it might go roughly as follows:

- [x] generate fiat-crypto low-level AST with only word sizes 32 and 64
- [x] break each 64-bit word into two 32-bit words (e.g., using mul_split)
- [x] translate that AST to `bedrock2.Syntax.cmd`

**Comment by JasonGross** [comment]
The second pass should be possible as a rewriter pass.  The third pass probably wants something like CStringification / the translation to fancy

**Comment by andres-erbsen** [comment]
I totally forgot about to today, but I'd like to brainstorm how to do the second pass (perhaps using the new and glorious lemma reification interface once it is working enough).

**Comment by JasonGross** [comment]
We probably need a special identity identifier which is `inline`, and then we have definitions and lemmas like
```coq
Definition assemble (x y : Z) : Z := ((x << 32) + y).
Definition break (x : Z) : Z * Z := (ident.cast word32 (x >> 32), ident.cast word32 (x mod 2^32)).

ident.cast word64 x = dlet yz := break x in inline (assemble (ident.cast word32 (fst yz)) (ident.cast word32 (snd yz))
break (inline (assemble (ident.cast word32 x) (ident.cast word32 y))) = (ident.cast word32 x, ident.cast word32 y)
(inline (assemble (ident.cast word32 x1) (ident.cast word32 x2)) + inline (assemble (ident.cast word32 y1) (ident.cast word32 y2)) = stuff involving addc
```
Basically, the idea I have is that we first replace all of the things known to be word64 with `assemble (break x)`, and then we push `break` inwards until it hits an `assemble ` which it then cancels with.

**Comment by JasonGross** [comment]
Note that there is some work-in-progress on this at https://github.com/mit-plv/fiat-crypto/compare/master...JasonGross:split-mul

It is mostly untested, and I probably won't get much of a chance to work on it before the end of the summer.

**Comment by JasonGross** [comment]
I have now put a bit more work into it and tested it, and it seems to mostly work well.  For 64-bit 25519 mulmod, we get code like
https://github.com/mit-plv/fiat-crypto/blob/79356b0c7189cdb636bda23580dc213e55c5d029/src/SlowPrimeSynthesisExamples.v#L79-L321

The only remaining `uint128` casts are ones that are immediately followed by a truncating `&` to 64-bits; we could hard-code an operation which is "unsigned truncating left shift" and use that instead.  So I think this pass is basically a success.

**Comment by andres-erbsen** [comment]
this looks awesome. could we just a rewrite rule that moves the uint128->uint64 conversion inside the &, and then inside the <<, and then cancel the uint64->uint128 conversation?

**Comment by JasonGross** [comment]
> could we just a rewrite rule that moves the uint128->uint64 conversion 

You're asking for something like `(uint64_t)((uint64_t)x150 << 13)`?  That's unsound, because casts don't truncate in the source language, they produce unspecified behavior when the number is out of bounds.  

Note that the >> | << & construct comes directly from the rewrite rule, so we can make it whatever we want as long as it's sound.
We could add an explicitly truncating cast and use that, or use `mod ` and recognize it when translating to bedrock2?

**Comment by andres-erbsen** [comment]
okay. could we have this rule after bounds analysis? having truncating cast also sounds fine though. in bedrock2 we have only one word type anyway.

**Comment by JasonGross** [comment]
This entire pass already runs after bounds analysis (which doesn't guarantee boundedness, only that the overall behavior is independent of what you choose to do when something is out of bounds.  Presumably we should fix this oversight some day.)

Do you want to see an explicit truncating cast, or are you fine with just recognizing `mod 2^k`?

**Comment by andres-erbsen** [comment]
just to state it explicitly: either option is fine by me

**Comment by JasonGross** [comment]
Let's do `mod 2^k`, then.  The current CStringification doesn't know how to print that; do you want it to be able to (are you planning to run after the existing C common type inference pass, or to split off before it?)

**Comment by andres-erbsen** [comment]
the common type pass is not verified, right? I think I should branch off before it. also whatever I do well only work if there is only one integer type remaining in the code.

**Comment by JasonGross** [comment]
> the common type pass is not verified, right?

That's correct

> also whatever I do well only work if there is only one integer type remaining in the code.

So you want the carry bits to be stored in uint64_t?  We can just tell bounds relaxation to not support 1-bit values.  Then we can expect code to end up with only one integer type.

**Comment by JasonGross** [comment]
Actually, hm, I think we might want to add an explicitly truncating left-shift, which we can just define as `truncating_shiftl bw x n := (x << n) mod 2^bw`.  Otherwise I don't see how to get rid of the 128-bit cast (though you can drop it and prove that you're allowed to in your pass, of course, though that seems needlessly painful)

**Comment by andres-erbsen** [comment]
I'm currently looking at a 32bit target, but yes, even carry bits in the same type as other integers. truncating shift sounds fine as well.

**Comment by JasonGross** [comment]
I will soon have a PR that adds `truncating_shiftl`, and shortly after that plan to rebase the branch I mentioned above and integrate the `truncating_shiftl` operation.

**Comment by JasonGross** [comment]
I have mostly gotten the rewrite to truncating_shiftl to work.  There is still a strange issue with `uint1` showing up, and a potentially related issue that I haven't managed to track down where making the carry bits be `uint64` breaks bounds extraction of the output bounds....

Anyway, the current code (https://github.com/mit-plv/fiat-crypto/compare/master...JasonGross:split-mul) is https://github.com/mit-plv/fiat-crypto/blob/5dc4f7159a0a9d16cb8e238ba72f507cfee8bd1d/src/SlowPrimeSynthesisExamples.v#L666-L908

Modulo the `uint1`s, how does this look to you @andres-erbsen ?

**Comment by JasonGross** [comment]
I have tracked down the issue with `uint1`, but fixing it seems to require some design that I'd like your input on @andres-erbsen .  There is a bounds check that ensures that we are passing the correct integer size to our adc/sbb functions, which happens during conversion to C:
https://github.com/mit-plv/fiat-crypto/blob/16b657a8bca9f2e04d66cf1be631a3344323eb2f/src/IR.v#L846
https://github.com/mit-plv/fiat-crypto/blob/16b657a8bca9f2e04d66cf1be631a3344323eb2f/src/IR.v#L879
Currently, we error if you try to store the carry in anything other than a uint1.  I can parameterize this part of the pipeline on an argument (I'm tempted to make it a typeclass) controlling the width of the carry argument, and then pipe that through from the higher levels.  But it's starting to feel a lot like spaghetti code, and I'd appreciate sitting down with you sometime and figuring out how we should structure the options related to this pass.

Anyway, other than this one issue, I believe the code is ready to have work done on translating from the IR we target (for C and Rust) to Bedrock.

**Comment by andres-erbsen** [comment]
We should be bottoming out in phoas, not the C "IR".

**Comment by jadephilipoom** [comment]
Some work on translating to bedrock2 in the bedrock-integration1 branch. I got it to work on Curve25519 64-bit, but 32-bit fails because in some places the code uses `combine_at_bitwidth` to make two 32-bit words a single 64-bit word [0]. Can we not do that? Am I instantiating something incorrectly here?

[0] https://github.com/mit-plv/fiat-crypto/blob/bedrock-integration1/src/Bedrock/CompilerTest.v#L1702

**Comment by JasonGross** [comment]
The issue is that for some reason we are not picking up the pattern that is supposed to remove `combine_at_bitwidth` for right-shift.  I suspect this is something to do with an inconsistency in where we prefix literals with casts and where we don't; I'll look into it when I get a chance.  Feel free to poke me again if I haven't said anything else here by the end of Monday.

**Comment by jadephilipoom** [comment]
I thought some of the more recent changes were supposed to fix this issue, but it's still there, so poke @JasonGross

**Comment by JasonGross** [comment]
Ah, we did make more progress this time, now there is a different issue.  The issue is that inlining is not happening correctly, because the rewriter can't inline complex combine_at_bitwidth statements, only simple ones.  The solution is to add let-bindings in the final >> rewrite rule as in the addition ones, i.e., change
```coq
             ; (forall xl xh offset,
                    0 < offset < bitwidth
                    -> doublewidth (cstZsingle_to_double xl xh >> singlewidth ('offset))
                       = cstZsingle_to_double
                           (Z.lor (singlewidth (singlewidth xl >> singlewidth ('offset)))
                                  (singlewidth
                                     (Z.truncating_shiftl
                                        (singlewidth ('bitwidth))
                                        (singlewidth xh)
                                        (singlewidth ('(bitwidth - offset))))))
                           (singlewidth xh >> singlewidth ('offset)))
```
to
```coq
             ; (forall xl xh offset,
                    0 < offset < bitwidth
                    -> doublewidth (cstZsingle_to_double xl xh >> singlewidth ('offset))
                       = dlet outl := singlewidth (Z.lor (singlewidth (singlewidth xl >> singlewidth ('offset)))
                                  (singlewidth
                                     (Z.truncating_shiftl
                                        (singlewidth ('bitwidth))
                                        (singlewidth xh)
                                        (singlewidth ('(bitwidth - offset)))))) in
                  dlet outh := singlewidth (singlewidth xh >> singlewidth ('offset)) in
cstZsingle_to_double outl outh
```
(Sorry for the atrocious indentation; I typed this on my phone)

**Comment by JasonGross** [comment]
#614 / #615 do in fact fix the issue you pointed at, but there is another missing rewrite rule: multiplying a double width by a single width and casting it to a double width has no rule (for doublewidth * 19).  I'll see if I can add a rule for that, too

**Comment by JasonGross** [comment]
I've updated #614 / #615 @jadephilipoom and now all the `ERROR`s are gone and it seems to compute correctly.  (I'll leave it to you to update the pasted output from the computation.)

**Comment by jadephilipoom** [comment]
Should we close this issue? There are still a couple of kinks to work out, like #750, but at this point it's more polishing than feature-adding. If there are no objections, I'll consider myself free to close it.
